sudo : required
services: 
 - docker


before_install:
 - docker build -t eafolabi/multi-dockerreact -f ./client/Dockerfile.dev ./client


script:
 - docker run eafolabi/multi-dockerreact npm test -- --coverage

after_success:
 - docker build -t eafolabi/multi-client ./client
 - docker build -t eafolabi/multi-nginx  ./nginx
 - docker build -t eafolabi/multi-worker ./worker
 - docker build -t eafolabi/multi-server ./server

 # Login to docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 #push image to docker hub
 - docker push eafolabi/multi-client
 - docker push eafolabi/multi-nginx
 - docker push eafolabi/multi-worker
 - docker push eafolabi/multi-server

deploy:
   provider: elasticbeanstalk
   region: "us-west-1"
   app: "multi-docker-react"
   env: "MultiDockerReact-env"
   bucket_name: "elasticbeanstalk-us-west-1-787818799103"
   bucket_path: "multi-docker-react"
   on:
     branch: master
   access_key_id: "$AWS_ACCESS_KEY"
   secret_access_key:
     secure: "$AWS_SECRET_KEY"



